# Generated by Django 5.2.8 on 2025-11-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_hex', models.CharField(blank=True, help_text='Ej: #FF0000 para rojo', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(blank=True, related_name='productos', to='home.color'),
        ),
    ]
